version: "3"

services:
  klusterx:
    build:
      context: .
      target: dev
    restart: unless-stopped
    volumes:
      - "./:/app"
      - "/app/node_modules"
    ports:
      - "${PORT}:${PORT}"
    stdin_open: true
