name: CI

on:
  push:
    branches:
      - '**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: yarn install

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
     
     - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install dependencies
        run: yarn install
      
      - name: Lint
        run: yarn lint
      
      - name: Run tests
        run: yarn test --u
      
      - name: Build
        run: yarn build

